#pragma once
#ifndef CCONS_h
#define CCONS_h

#define S_MENU						"Main menu"
#define S_MAIN						"main"
#define S_DELETE_ALL				"Deleting :"
#define S_CREATE_N					"Create"
#define S_CREATE_C					"new"
#define S_DISPLAY_N					"Print"
#define S_DISPLAY_C					"print"
#define S_DELETE_N					"Delete"
#define S_DELETE_C					"delete"
#define S_EDIT_N					"Edit"
#define S_EDIT_C					"edit"
#define S_CREATE_NEW_TAB_N			"Create new table"
#define S_CREATE_NEW_TAB_C			"newArr"
#define S_CLONE_TAB_N				"Copy array"
#define S_CLONE_TAB_C				"copy"
#define S_DISPLAY_ALL_N				"Print all"
#define S_DISPLAY_ALL_C				"printAll"
#define S_PRINT_ONE_TAB_N			"Print single array"
#define S_PRINT_ONE_TAB_C			"printOne"
#define S_DELETE_ALL_TAB_N			"Delete all arrays"
#define S_DELETE_ALL_TAB_C			"deleteAll"
#define S_DELETE_ONE_N				"Delete one array"
#define S_DELETE_ONE_C				"deleteOne"
#define S_CHANGE_NAME_N				"Change array's name"
#define S_CHANGE_NAME_C				"changeName"
#define S_CHANGE_VAL_N				"Change value in a array"
#define S_CHANGE_VAL_C				"changeVal"
#define S_CHANGE_LEN_N				"Change length of an array"
#define S_CHANGE_LEN_C				"changeLen"
#define S_ENTER_COMM				"Enter command : "
#define S_MENU_EXIT					"To exit enter: exit"
#define S_MENU_BACK					"To return to previous menu enter: back"
#define S_MENU_SEARCH				"To search command/menu path enter: search (*enter name here*)"
#define S_MENU_HELP					"If u don't know what command does enter: help (*enter name here*) "
#define S_TEXT_CREATE				"Creating  arrays submenu "
#define S_TEXT_PRINT				"Displaying arrays submenu"
#define S_TEXT_DELETE				"Deleting arrays submenu"
#define S_TEXT_EDIT					"Editing arrays submenu"
#define S_TEXT_NEW					"Command which creates array"
#define S_TEXT_CLONE				"Command wich coppies chosen array"
#define S_TEXT_PRINTALL				"Command which displays all arrays"
#define S_TEXT_PRINTONE				"Command which displays  chosen array"
#define S_TEXT_DELETEALL			"Command which deletes all arrays"
#define S_TEXT_DELETEONE			"Command which deletes chosen array"
#define S_TEXT_CHANGENAME			"Command which changes array's name"
#define S_TEXT_CHANGEVAL			"Command which changes a value on chosen position "
#define S_TEXT_CHANELEN				"Command which changes length of chosen array"
#define S_EMPTY_COMMAND				"Empty command"
#define S_DEF_COMMAND				"defCom"
#define S_DEF_NAME					"Default command"
#define S_WHAT_TAB_INPUT			"Chose array number: (-1 -> help)"
#define S_EMPTY_TAB					"There are no arrays !!!"
#define S_ENTER_LEN_INPUT			"Enter length: "
#define S_WHAT_NAME					"Enter name: "
#define S_WHAT_VAL					"Enter value: "
#define S_WHAT_CELL					"Which possiton ? :(-1 -> help)"
#define S_RANGE						"Possiton range: 0 - "
#define S_DEL_SUCC					"Deleting was successful"
#define S_DEF_TAB					"Default array (single) enter 1 "
#define S_CUSTOM_TAB				"Custom array enter 2"
#define S_DEF_TAB_MUL				"Default array (multiple) enter 3 "
#define S_HOW_MANY					"How many do you want to create ?:"
#define S_WRONG_COMM				"There is no such command. Try again:)"
#define S_ERROR						"Error that shouldn't happen"
#define S_WRONG_COMMAND				"Sub_Menu"
#define S_CSAVELOAD_DANE_TXT		"dane.txt"
#define S_CSAVELOAD_DATA_EXCEPTION	"ERROR: read file is not accesible ."
#define S_CSAVELOAD_BAD_STRING		"Invlaid string!"
#define S_CSAVELOAD_INTERFACE_BACK	"back"
#define S_CSAVELOAD_INDEX			"index: "
#define S_COLON						":  "
#define S_OPEN_BRACKET				"  ("
#define S_CLOSED_BRACKET			")  "
#define S_BACK						"back"
#define S_REC_1						"(‘"
#define S_REC_2						"’,"
#define S_REC_3						"‘"
#define S_REC_4						"’;"
#define S_REC_5						","
#define S_REC_6						")"
#define S_REC_7						"[‘"
#define S_REC_8						"’,‘"
#define S_REC_9						"Pick a number from "
#define S_REC_10					" to "
#define S_ARROW						"->"
#define S_EXIT						"exit"
#define S_SEARCH					"search"
#define S_HELP						"help"
#define S_EMPTY_STRING				""
#define I_DEFAULT_TABLE_SIZE		10
#define S_DEFAULT_TABLE_NAME		"DEFAULT_NAME"
#define S_COPPY_END					"_copy"
#define S_COPY						"copy: '"
#define S_SPACE						" "
#define S_LEN						"length: "
#define S_COMMA						", "
#define S_CSAVELOAD_ERROR_1			"	Expected: '(' or '[' or ')'"
#define S_CSAVELOAD_ERROR_2			"   Expected: ')'"
#define S_CSAVELOAD_ERROR_3			"   Expected: ';'"
#define S_CSAVELOAD_ERROR_4			"   Expected: '(' or '[' or ','"
#define S_CSAVELOAD_ERROR_5			"   Expected: ','"
#define S_CSAVELOAD_ERROR_6			"   Expected: '('"
#define S_CSAVELOAD_ERROR_7			"   Expected: ']'"
#define S_CSAVELOAD_ERROR_8			"   Expected: '’'"
#define S_CSAVELOAD_ERROR_9			"   Expected: '‘'"
#define S_CSAVELOAD_ERROR_10		"   Expected: ',' or ')'"
#define S_PART  "------------------------------------------------------------------------------------------------------------------------"
#define S_DOT  ". "
#define C_CSAVELOAD_CORRECT_PALE_RIGHT_OPEN ')'
#define C_CSAVELOAD_CORRECT_PALE_LEFT_OPEN '('
#define C_CSAVELOAD_CORRECT_PALE_RIGHT_CLOSE ']'
#define C_CSAVELOAD_CORRECT_PALE_LEFT_CLOSE '['
#define C_CSAVELOAD_CORRECT_COMMA ','
#define C_CSAVELOAD_CORRECT_SEMICOLON ';'
#define C_CSAVELOAD_CORRECT_APOSTROPHE_RIGHT '’'
#define C_CSAVELOAD_CORRECT_APOSTROPHE_LEFT '‘'
#define C_NEWLINE '\n'
#define C_SPACE ' '
#endif // !CCONS_h